# Generated by cpp11: do not edit by hand

cpp_read_dbf_meta <- function(filename) {
  .Call("_shp_cpp_read_dbf_meta", filename, PACKAGE = "shp")
}

cpp_read_dbf <- function(filename) {
  invisible(.Call("_shp_cpp_read_dbf", filename, PACKAGE = "shp"))
}
